// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Territorial.Meta.Infrastructure.Persistence;

#nullable disable

namespace Territorial.Meta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetaDbContext))]
    [Migration("20260731230609_AddParticipantLeftAt")]
    partial class AddParticipantLeftAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Territorial.Meta.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("map_id");

                    b.Property<int>("MaxActors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_actors");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("WsUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("ws_url");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_matches_state");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Territorial.Meta.Domain.Matches.MatchParticipant", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT")
                        .HasColumnName("match_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("left_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<byte>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Color", "Territorial.Meta.Domain.Matches.MatchParticipant.Color#HsvColor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Hue")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_hue");

                            b1.Property<int>("Saturation")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_saturation");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_value");
                        });

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_match_participants_player_id");

                    b.HasIndex("MatchId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_match_participants_match_id_slot");

                    b.ToTable("match_participants", (string)null);
                });

            modelBuilder.Entity("Territorial.Meta.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Color", "Territorial.Meta.Domain.Players.Player.Color#HsvColor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Hue")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_hue");

                            b1.Property<int>("Saturation")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_saturation");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_value");
                        });

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Territorial.Meta.Domain.Matches.MatchParticipant", b =>
                {
                    b.HasOne("Territorial.Meta.Domain.Matches.Match", null)
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Territorial.Meta.Domain.Matches.Match", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
