// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Territorial.Meta.Infrastructure.Persistence;

#nullable disable

namespace Territorial.Meta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetaDbContext))]
    partial class MetaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Territorial.Meta.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Color", "Territorial.Meta.Domain.Players.Player.Color#HsvColor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Hue")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_hue");

                            b1.Property<int>("Saturation")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_saturation");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("color_value");
                        });

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
